[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.30", features = ["rand", "global-context"] }
rand = "0.8"
sha2 = "0.10.0"
hex = "0.4.3"
